spring:
  application:
    name: FINO
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    include: db
  devtools:
    restart:
      enabled: false

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security: DEBUG
    com.kangwon.fino: DEBUG