spring:
  application:
    name: FINO
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    include: db, jwt
  devtools:
    restart:
      enabled: false

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.kangwon.fino

location:
  auth:
    allowed-distance-meters: 150.0 # 허용 오차 범위 (미터 단위)